# Change these first
owner: theboatymcboatface # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:

  - name: BentleyHensel.com
    url: https://bentleyhensel.com/
    method: GET
  - name: AdminyMcAdminFace
    url: https//portainer.beltway-buzz.com
  - name: Beltway Buzzy
    url: https://media.beltway-buzz.com
  - name: Ashley & Abby
    url: https://ashleyabby.info
  - name: Magic
    url: https://magic.bfhensel.com
  - name: A11yWatch Frontend
    url: https://a11ywatch-frontend.public-sector-a11y.app.civicactions.net/
  - name: A11yWatch Backend
    url: https://a11ywatch-backend.public-sector-a11y.app.civicactions.net/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bentleyhensel.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bentley Hensel Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Current Intro Message
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
